// MDIアイコン名からパスを取得するヘルパー
import {
  mdiDice6,
  mdiCoffee,
  mdiGlassMugVariant,
  mdiSoccer,
  mdiGamepadVariant,
  mdiMovie,
  mdiBookOpenPageVariant,
  mdiMusic,
  mdiRun,
  mdiWeightLifter,
  mdiYoga,
  mdiCamera,
  mdiPalette,
  mdiLaptop,
  mdiForum,
  mdiPencil,
  mdiBullhorn,
  mdiAccount,
  mdiHandWave,
  mdiPlus,
  mdiCheck,
  mdiCheckCircle,
  mdiClose,
  mdiChevronRight,
  mdiChevronLeft,
  mdiMagnify,
  mdiLogout,
  mdiCog,
  mdiHome,
  mdiHeart,
  mdiStar,
  mdiMapMarker,
  mdiCalendar,
  mdiClock,
  mdiAccountGroup,
  mdiSend,
  mdiDotsVertical,
  mdiCity,
  mdiCastle,
  mdiCrosshairsGps,
  mdiMapMarkerRadius,
  mdiTrain,
  mdiEye,
  mdiFilterVariant,
} from '@mdi/js'

// アイコン名からパスへのマッピング
const iconMap: Record<string, string> = {
  // カテゴリアイコン
  mdiDice6,
  mdiCoffee,
  mdiGlassMugVariant,
  mdiSoccer,
  mdiGamepadVariant,
  mdiMovie,
  mdiBookOpenPageVariant,
  mdiMusic,
  mdiRun,
  mdiWeightLifter,
  mdiYoga,
  mdiCamera,
  mdiPalette,
  mdiLaptop,
  mdiForum,
  // UIアイコン
  mdiPencil,
  mdiBullhorn,
  mdiAccount,
  mdiHandWave,
  mdiPlus,
  mdiCheck,
  mdiCheckCircle,
  mdiClose,
  mdiEye,
  mdiChevronRight,
  mdiChevronLeft,
  mdiMagnify,
  mdiLogout,
  mdiCog,
  mdiHome,
  mdiHeart,
  mdiStar,
  mdiMapMarker,
  mdiCalendar,
  mdiClock,
  mdiAccountGroup,
  mdiSend,
  mdiDotsVertical,
  mdiCity,
  mdiCastle,
  // 位置情報アイコン
  mdiCrosshairsGps,
  mdiMapMarkerRadius,
  mdiTrain,
  mdiFilterVariant,
}

/**
 * MDIアイコン名からSVGパスを取得
 * @param iconName - MDIアイコン名（例: 'mdiDice6'）
 * @returns SVGパス文字列、見つからない場合は空文字
 */
export function getIconPath(iconName: string): string {
  return iconMap[iconName] || ''
}

// 個別エクスポート（直接インポート用）
export {
  mdiDice6,
  mdiCoffee,
  mdiGlassMugVariant,
  mdiSoccer,
  mdiGamepadVariant,
  mdiMovie,
  mdiBookOpenPageVariant,
  mdiMusic,
  mdiRun,
  mdiWeightLifter,
  mdiYoga,
  mdiCamera,
  mdiPalette,
  mdiLaptop,
  mdiForum,
  mdiPencil,
  mdiBullhorn,
  mdiAccount,
  mdiHandWave,
  mdiPlus,
  mdiCheck,
  mdiCheckCircle,
  mdiClose,
  mdiEye,
  mdiChevronRight,
  mdiChevronLeft,
  mdiMagnify,
  mdiLogout,
  mdiCog,
  mdiHome,
  mdiHeart,
  mdiStar,
  mdiMapMarker,
  mdiCalendar,
  mdiClock,
  mdiAccountGroup,
  mdiSend,
  mdiDotsVertical,
  mdiCity,
  mdiCastle,
  mdiCrosshairsGps,
  mdiMapMarkerRadius,
  mdiTrain,
  mdiFilterVariant,
}
